services:
  # Frontend Service
  frontend:
    build:
      context: ./kimdat-fe
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
    container_name: kimdat-frontend
    env_file:
      - ./.env
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - kimdat-network

  # Nginx Frontend Server (Static Files Only)
  nginx:
    image: nginx:alpine
    container_name: kimdat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
    networks:
      - kimdat-network

  # Backend API Service
  backend:
    build:
      context: ./kimdat-be
      dockerfile: Dockerfile
      target: production
    container_name: kimdat-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./kimdat-be/images:/app/images
    networks:
      - kimdat-network

volumes:
  frontend_dist:
    driver: local

networks:
  kimdat-network:
    driver: bridge 